REFLECTOR_B = {
    "A": "Y",
    "Y": "A",
    "B": "R",
    "R": "B",
    "C": "U",
    "U": "C",
    "D": "H",
    "H": "D",
    "E": "Q",
    "Q": "E",
    "F": "S",
    "S": "F",
    "G": "L",
    "L": "G",
    "I": "P",
    "P": "I",
    "J": "X",
    "X": "J",
    "K": "N",
    "N": "K",
    "M": "O",
    "O": "M",
    "T": "Z",
    "Z": "T",
    "V": "W",
    "W": "V",
}

REFLECTOR_C = {
    "A": "F",
    "F": "A",
    "B": "V",
    "V": "B",
    "C": "P",
    "P": "C",
    "D": "J",
    "J": "D",
    "E": "I",
    "I": "E",
    "G": "O",
    "O": "G",
    "H": "Y",
    "Y": "H",
    "K": "R",
    "R": "K",
    "L": "Z",
    "Z": "L",
    "M": "X",
    "X": "M",
    "N": "W",
    "W": "N",
    "Q": "T",
    "T": "Q",
    "S": "U",
    "U": "S",
}

# ---------------------------------------------------------------------------
# Rotor (Walzen) wirings. Unlike the reflectors these are NOT symmetric:
# each is a one-to-one substitution from the entry side to the output side,
# so the reverse pass through the rotor uses the inverse of the dictionary.
# Labelled 0, 1, 2 here; historically these are Enigma rotors I, II, III.
# ---------------------------------------------------------------------------

# Rotor 0  (Enigma I,  wiring string: EKMFLGDQVZNTOWYHXUSPAIBRCJ)
ROTOR_0 = {
    "A": "E",
    "B": "K",
    "C": "M",
    "D": "F",
    "E": "L",
    "F": "G",
    "G": "D",
    "H": "Q",
    "I": "V",
    "J": "Z",
    "K": "N",
    "L": "T",
    "M": "O",
    "N": "W",
    "O": "Y",
    "P": "H",
    "Q": "X",
    "R": "U",
    "S": "S",
    "T": "P",
    "U": "A",
    "V": "I",
    "W": "B",
    "X": "R",
    "Y": "C",
    "Z": "J",
}

# Rotor 1  (Enigma II, wiring string: AJDKSIRUXBLHWTMCQGZNPYFVOE)
ROTOR_1 = {
    "A": "A",
    "B": "J",
    "C": "D",
    "D": "K",
    "E": "S",
    "F": "I",
    "G": "R",
    "H": "U",
    "I": "X",
    "J": "B",
    "K": "L",
    "L": "H",
    "M": "W",
    "N": "T",
    "O": "M",
    "P": "C",
    "Q": "Q",
    "R": "G",
    "S": "Z",
    "T": "N",
    "U": "P",
    "V": "Y",
    "W": "F",
    "X": "V",
    "Y": "O",
    "Z": "E",
}

# Rotor 2  (Enigma III, wiring string: BDFHJLCPRTXVZNYEIWGAKMUSQO)
ROTOR_2 = {
    "A": "B",
    "B": "D",
    "C": "F",
    "D": "H",
    "E": "J",
    "F": "L",
    "G": "C",
    "H": "P",
    "I": "R",
    "J": "T",
    "K": "X",
    "L": "V",
    "M": "Z",
    "N": "N",
    "O": "Y",
    "P": "E",
    "Q": "I",
    "R": "W",
    "S": "G",
    "T": "A",
    "U": "K",
    "V": "M",
    "W": "U",
    "X": "S",
    "Y": "Q",
    "Z": "O",
}

# ---------------------------------------------------------------------------
# Inverse rotor wirings, used for the return pass (after the reflector).
# Each is the reverse mapping of the corresponding ROTOR_n dictionary, i.e.
# {value: key for key, value in ROTOR_n.items()}.
# ---------------------------------------------------------------------------

# Inverse of Rotor 0
ROTOR_0_INV = {
    "A": "U",
    "B": "W",
    "C": "Y",
    "D": "G",
    "E": "A",
    "F": "D",
    "G": "F",
    "H": "P",
    "I": "V",
    "J": "Z",
    "K": "B",
    "L": "E",
    "M": "C",
    "N": "K",
    "O": "M",
    "P": "T",
    "Q": "H",
    "R": "X",
    "S": "S",
    "T": "L",
    "U": "R",
    "V": "I",
    "W": "N",
    "X": "Q",
    "Y": "O",
    "Z": "J",
}

# Inverse of Rotor 1
ROTOR_1_INV = {
    "A": "A",
    "B": "J",
    "C": "P",
    "D": "C",
    "E": "Z",
    "F": "W",
    "G": "R",
    "H": "L",
    "I": "F",
    "J": "B",
    "K": "D",
    "L": "K",
    "M": "O",
    "N": "T",
    "O": "Y",
    "P": "U",
    "Q": "Q",
    "R": "G",
    "S": "E",
    "T": "N",
    "U": "H",
    "V": "X",
    "W": "M",
    "X": "I",
    "Y": "V",
    "Z": "S",
}

# Inverse of Rotor 2
ROTOR_2_INV = {
    "A": "T",
    "B": "A",
    "C": "G",
    "D": "B",
    "E": "P",
    "F": "C",
    "G": "S",
    "H": "D",
    "I": "Q",
    "J": "E",
    "K": "U",
    "L": "F",
    "M": "V",
    "N": "N",
    "O": "Z",
    "P": "H",
    "Q": "Y",
    "R": "I",
    "S": "X",
    "T": "J",
    "U": "W",
    "V": "L",
    "W": "R",
    "X": "K",
    "Y": "O",
    "Z": "M",
}
